# EnPluzz
# Copyright (C) 2025  Elioty <roadkiller.cl@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.1.4 on 2025-05-17 10:03

import django.db.models.deletion
import enpluzz_core.modelHelper
import enpluzz_dragons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enpluzz_core', '0001_initial'),
        ('enpluzz_heroes', '0002_alter_hero_family_alter_hero_mana_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_dra_enp_id_cfaea7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DragonSpiritBonusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_dra_enp_id_117422_idx')],
            },
        ),
        migrations.CreateModel(
            name='DragonSpiritBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('stat_bonuses', enpluzz_core.modelHelper.JSONFieldFromJson(default=enpluzz_dragons.models.DragonSpiritBonus._default_stat_bonuses)),
                ('bonus_type', enpluzz_core.modelHelper.ForeignKeyFromJson(on_delete=django.db.models.deletion.PROTECT, to='enpluzz_dragons.dragonspiritbonustype', to_field='enp_id')),
            ],
        ),
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('can_be_received_date', enpluzz_core.modelHelper.DateTimeFieldFromJson(null=True)),
                ('base_attack', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('base_defense', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('base_health', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('assist_skill', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='enpluzz_dragons.assistskill', to_field='enp_id')),
                ('assist_skill_mana_speed', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='enpluzz_heroes.manaspeed', to_field='enp_id')),
                ('element', enpluzz_core.modelHelper.ForeignKeyFromJson(on_delete=django.db.models.deletion.PROTECT, to='enpluzz_core.element', to_field='enp_id')),
                ('mana_speed', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dragons', to='enpluzz_heroes.manaspeed', to_field='enp_id')),
                ('origin', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.origin', to_field='enp_id')),
                ('rarity', enpluzz_core.modelHelper.ForeignKeyFromJson(on_delete=django.db.models.deletion.PROTECT, to='enpluzz_core.rarity', to_field='enp_id')),
                ('special_skill', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.specialskill', to_field='enp_id')),
                ('trainer_type', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.trainertype', to_field='enp_id')),
                ('dragon_spirit_class_bonuses', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='enpluzz_dragons.dragonspiritbonus', to_field='enp_id')),
                ('dragon_spirit_element_bonuses', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='enpluzz_dragons.dragonspiritbonus', to_field='enp_id')),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_dra_enp_id_a156a2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dragonspiritbonus',
            index=models.Index(fields=['enp_id'], name='enpluzz_dra_enp_id_aae705_idx'),
        ),
    ]
