# EnPluzz
# Copyright (C) 2025  Elioty <roadkiller.cl@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.1.4 on 2025-06-21 21:02

import django.db.models.deletion
import enpluzz_core.modelHelper
import enpluzz_heroes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enpluzz_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_affected', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255)),
                ('type_of_target', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255)),
                ('effect_type', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, null=True)),
                ('power_multiplier_per_mil', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('power_multiplier_increment_per_level_per_mil', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('has_fixed_power', enpluzz_core.modelHelper.BooleanFieldFromJson(default=False)),
                ('minor_power_multiplier_override_per_mil', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('minor_power_multiplier_override_increment_per_level_per_mil', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AetherGifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_fe0833_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('talent_skill_act_per_mil_per_node', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('improved_talent_skill_act_per_mil_per_node', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_aa314a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CostumeBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('stat_bonuses', enpluzz_core.modelHelper.JSONFieldFromJson(default=enpluzz_heroes.models.CostumeBonus._default_stat_bonuses)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_6cdc26_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_0eaa48_idx')],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('deactivated_until', enpluzz_core.modelHelper.DateTimeFieldFromJson(null=True)),
                ('hidden_until', enpluzz_core.modelHelper.DateTimeFieldFromJson(null=True)),
                ('is_realm', enpluzz_core.modelHelper.BooleanFieldFromJson(default=False)),
                ('use_custom_realm_description', enpluzz_core.modelHelper.BooleanFieldFromJson(default=False)),
                ('active_on_fully_ascended_members_only', enpluzz_core.modelHelper.BooleanFieldFromJson(default=False)),
                ('order', models.IntegerField(default=None, null=True)),
                ('family_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enpluzz_heroes.familyset', to_field='enp_id')),
            ],
        ),
        migrations.CreateModel(
            name='ManaSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('max_mana', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('alternating_mana_modifier_per_mil', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('charged_mana_modifiers_per_mil', enpluzz_core.modelHelper.JSONFieldFromJson(default=list)),
                ('show_extra_info', enpluzz_core.modelHelper.BooleanFieldFromJson(default=False)),
                ('order', models.IntegerField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_80de3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', models.CharField(max_length=255, unique=True)),
                ('order', models.IntegerField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_85ce80_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpecialSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('max_level', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('accuracy_modifier_per_mil', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('direct_effect', enpluzz_core.modelHelper.OneToOneFieldFromJson(default=enpluzz_heroes.models.DirectEffect, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.directeffect')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_830fa1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp_id', enpluzz_core.modelHelper.CharFieldFromJson(max_length=255, unique=True)),
                ('has_improved_talent_skill', enpluzz_core.modelHelper.BooleanFieldFromJson(default=False)),
                ('can_be_received_date', enpluzz_core.modelHelper.DateTimeFieldFromJson(null=True)),
                ('is_default_rider', enpluzz_core.modelHelper.BooleanFieldFromJson(default=False)),
                ('base_attack', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('base_defense', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('base_health', enpluzz_core.modelHelper.IntegerFieldFromJson(default=0)),
                ('aether_gift', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.aethergifts', to_field='enp_id')),
                ('class_type', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.classtype', to_field='enp_id')),
                ('costume_bonus', enpluzz_core.modelHelper.ForeignKeyFromJson(default='default', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='enpluzz_heroes.costumebonus', to_field='enp_id')),
                ('element', enpluzz_core.modelHelper.ForeignKeyFromJson(on_delete=django.db.models.deletion.PROTECT, to='enpluzz_core.element', to_field='enp_id')),
                ('family', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heroes', to='enpluzz_heroes.family', to_field='enp_id')),
                ('parent_hero', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costumes', to='enpluzz_heroes.hero', to_field='enp_id')),
                ('rarity', enpluzz_core.modelHelper.ForeignKeyFromJson(on_delete=django.db.models.deletion.PROTECT, to='enpluzz_core.rarity', to_field='enp_id')),
                ('mana_speed', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heroes', to='enpluzz_heroes.manaspeed', to_field='enp_id')),
                ('origin', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.origin', to_field='enp_id')),
                ('special_skill', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.specialskill', to_field='enp_id')),
                ('trainer_type', enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, to='enpluzz_heroes.trainertype', to_field='enp_id')),
            ],
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_8e9b00_idx'),
        ),
        migrations.AddIndex(
            model_name='specialskill',
            index=models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_baf013_idx'),
        ),
        migrations.AddIndex(
            model_name='hero',
            index=models.Index(fields=['enp_id'], name='enpluzz_her_enp_id_1e104e_idx'),
        ),
        migrations.AddIndex(
            model_name='hero',
            index=models.Index(fields=['parent_hero'], name='enpluzz_her_parent__761702_idx'),
        ),
    ]
