# EnPluzz
# Copyright (C) 2025  Elioty <roadkiller.cl@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 5.1.4 on 2025-03-29 13:48

import django.db.models.deletion
import enpluzz_core.modelHelper
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enpluzz_heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='family',
            field=enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heroes', to='enpluzz_heroes.family', to_field='enp_id'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='mana_speed',
            field=enpluzz_core.modelHelper.ForeignKeyFromJson(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='heroes', to='enpluzz_heroes.manaspeed', to_field='enp_id'),
        ),
    ]
